# Notebook 1 : Découverte de Pandas

In [2]:
import pandas as pd

## Iris

Nous considérons le jeu de données connu sous le nom des [Iris de Fisher](https://fr.wikipedia.org/wiki/Iris_de_Fisher). Répondez aux questions suivantes à l'aide du module Pandas.

1. Charger le jeu de données dans un dataframe `iris` à partir du fichier `iris.csv` et afficher le dataframe.

In [3]:
iris = pd.read_csv("data/iris.csv")
print(iris)

     SepalLength  SepalWidth  PetalLength  PetalWidth    Species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

2. Sélectionner les variables `PetalWidth` et `Species`.

In [4]:
print(iris.filter(items=["PetalLength", "Species"]))

     PetalLength    Species
0            1.4     setosa
1            1.4     setosa
2            1.3     setosa
3            1.5     setosa
4            1.4     setosa
..           ...        ...
145          5.2  virginica
146          5.0  virginica
147          5.2  virginica
148          5.4  virginica
149          5.1  virginica

[150 rows x 2 columns]

3. Extraire le sous-dataframe qui contient uniquement les iris des espèces `versicolor` ou `virginica`.

In [5]:
print(iris[(iris["Species"] == "versicolor") | (iris["Species"] == "virginica")])

     SepalLength  SepalWidth  PetalLength  PetalWidth     Species
50           7.0         3.2          4.7         1.4  versicolor
51           6.4         3.2          4.5         1.5  versicolor
52           6.9         3.1          4.9         1.5  versicolor
53           5.5         2.3          4.0         1.3  versicolor
54           6.5         2.8          4.6         1.5  versicolor
..           ...         ...          ...         ...         ...
145          6.7         3.0          5.2         2.3   virginica
146          6.3         2.5          5.0         1.9   virginica
147          6.5         3.0          5.2         2.0   virginica
148          6.2         3.4          5.4         2.3   virginica
149          5.9         3.0          5.1         1.8   virginica

[100 rows x 5 columns]

4. Compter le nombre d'iris de l'espèce `setosa`.

In [6]:
iris[iris["Species"] == "setosa"]["Species"].count()

np.int64(50)

5. Calculer la moyenne de la variable `PetalWidth` pour les iris de l'espèce `versicolor`.

In [7]:
iris[iris["Species"] == "versicolor"]["PetalWidth"].mean()

np.float64(1.3259999999999998)

6. Ajouter une variable `SumWidth` qui contient la somme des variables `PetalWidth` et `SepalWidth`.

In [8]:
iris["SumWidth"] = iris["PetalWidth"] + iris["SepalWidth"]
iris

     SepalLength  SepalWidth  PetalLength  PetalWidth    Species  SumWidth
0            5.1         3.5          1.4         0.2     setosa       3.7
1            4.9         3.0          1.4         0.2     setosa       3.2
2            4.7         3.2          1.3         0.2     setosa       3.4
3            4.6         3.1          1.5         0.2     setosa       3.3
4            5.0         3.6          1.4         0.2     setosa       3.8
..           ...         ...          ...         ...        ...       ...
145          6.7         3.0          5.2         2.3  virginica       5.3
146          6.3         2.5          5.0         1.9  virginica       4.4
147          6.5         3.0          5.2         2.0  virginica       5.0
148          6.2         3.4          5.4         2.3  virginica       5.7
149          5.9         3.0          5.1         1.8  virginica       4.8

[150 rows x 6 columns]

7. Calculer la moyenne et la variance de la variable `SepalLength` pour chaque espèce.

In [9]:
iris.groupby("Species")["SepalLength"].agg(["mean", "var"])

             mean       var
Species
setosa      5.006  0.124249
versicolor  5.936  0.266433
virginica   6.588  0.404343

8. Calculer la moyenne de toutes les variables pour chaque espèce. Afficher le résultat au format large et au format long.

In [10]:
iris.groupby("Species").mean()

            SepalLength  SepalWidth  PetalLength  PetalWidth  SumWidth
Species
setosa            5.006       3.428        1.462       0.246     3.674
versicolor        5.936       2.770        4.260       1.326     4.096
virginica         6.588       2.974        5.552       2.026     5.000

In [11]:
print(
    iris.groupby("Species")
        .mean()
        .reset_index()
        .melt(id_vars="Species", var_name="Variable", value_name="Moyenne")
)

       Species     Variable  Moyenne
0       setosa  SepalLength    5.006
1   versicolor  SepalLength    5.936
2    virginica  SepalLength    6.588
3       setosa   SepalWidth    3.428
4   versicolor   SepalWidth    2.770
5    virginica   SepalWidth    2.974
6       setosa  PetalLength    1.462
7   versicolor  PetalLength    4.260
8    virginica  PetalLength    5.552
9       setosa   PetalWidth    0.246
10  versicolor   PetalWidth    1.326
11   virginica   PetalWidth    2.026
12      setosa     SumWidth    3.674
13  versicolor     SumWidth    4.096
14   virginica     SumWidth    5.000

## Houston flights

Nous considérons le jeux de données `hflights` relatif à des vols au départ des aéroports *Houston George Bush Intercontinental Airport* (IAH) et *William P. Hobby Airport* (HOU).

1. Charger le jeu de données dans un dataframe `hflights` à partir du fichier `hflights.csv`

2. Sélectionner les variable `Dest`, `Distance`, `TaxiIn` et `TaxiOut` avec la méthode `filter`.

3. Sélectionner les variables `DepTime`, `ArrTime`, `ActualElapsedTime` et `AirTime` avec la méthode `filter` et le paramètre `like`.

4. Ajouter une variable `ActualGroundTime` qui correspond à `ActualElapsedTime` moins `AirTime`.

5. Ajouter une variable `AverageSpeed` qui donne la vitesse moyenne du vol et ordonner la table selon les valeurs décroissantes de cette variable.

6. Sélectionner les vols à destination de `JFK`.

7. Compter le nombre de vols à destination de `JFK`.

8. Agréger les données `hflights` pour obtenir :
- `n` : le nombre total de vols,
- `n_dest`: le nombre total de destinations distinctes,
- `n_carrier` : le nombre total de compagnies distinctes.

9. Agréger les données des vols de la compagnie `AA` pour obtenir :
- le nombre total de vols,
- le nombre total de vols annulés,
- la valeur moyenne de `ArrDelay`.

10. Calculer pour chaque compagnie :
- le nombre total de vols,
- la valeur moyenne de `AirTime`.

11. Ordonner les compagnies en fonction des retards moyens au départ.