# Notebook 2 : Pandas avancé

In [12]:
import pandas as pd

## Tennis

Nous considérons les données des résultats des matchs de tennis masculin des tournois de Roland Garros et Wimbledon en 2013. La liste des variables et leur signification se trouvent sur [cette page](https://archive.ics.uci.edu/dataset/300/tennis+major+tournament+match+statistics) dans la section *Additional Variable Information*.

1. Commencer par charger le jeu de données relatif au tournoi de Roland Garros dans un dataframe `rg` à partir du fichier `rolandgarros2013.csv`.

In [13]:
rg = pd.read_csv("data/rolandgarros2013.csv")
rg

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPC.2,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2
0,Pablo Carreno-Busta,Roger Federer,1,0,0,3,62,27,38,11,...,7,7,14,18,88,6,6,6.0,NaN,NaN
1,Somdev Devvarman,Daniel Munoz-De La Nava,1,1,3,0,62,54,38,22,...,1,16,22,25,106,3,3,5.0,NaN,NaN
2,Tobias Kamke,Paolo Lorenzi,1,1,3,2,62,53,38,15,...,10,18,19,27,139,3,3,6.0,6.0,3.0
3,Julien Benneteau,Ricardas Berankis,1,1,3,1,72,87,28,19,...,4,13,33,43,149,6,3,7.0,6.0,NaN
4,Lukas Lacko,Sam Querrey,1,0,0,3,52,31,48,22,...,4,7,12,13,93,6,6,6.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,Rafael Nadal,Stanislas Wawrinka,5,1,3,0,75,40,25,11,...,1,5,16,30,64,2,3,1.0,NaN,NaN
121,Novak Djokovic,Tommy Haas,5,1,3,0,64,41,36,22,...,2,2,2,17,84,3,6,5.0,NaN,NaN
122,David Ferrer,Jo-Wilfried Tsonga,6,1,3,0,60,35,40,23,...,2,5,7,16,84,1,6,2.0,NaN,NaN
123,Novak Djokovic,Rafael Nadal,6,0,2,3,67,76,33,30,...,8,16,15,26,177,6,3,6.0,6.0,9.0
124,Rafael Nadal,David Ferrer,7,1,3,0,70,43,30,11,...,3,12,10,14,72,3,2,3.0,NaN,NaN

2. Afficher les noms des demi-finalistes.

In [14]:
rg[rg.Round == 6]

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPC.2,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2
122,David Ferrer,Jo-Wilfried Tsonga,6,1,3,0,60,35,40,23,...,2,5,7,16,84,1,6,2.0,NaN,NaN
123,Novak Djokovic,Rafael Nadal,6,0,2,3,67,76,33,30,...,8,16,15,26,177,6,3,6.0,6.0,9.0

3. Calculer le nombre moyen d'aces par match dans le tournoi.

In [15]:
rg["Acematch"] = rg["ACE.1"] + rg["ACE.2"]
rg["Acematch"].mean()

np.float64(12.688)

4. Combien y a-t-il eu d'aces par match en moyenne à chaque niveau du tournoi ?

In [16]:
rg["Acematch"] = rg["ACE.1"] + rg["ACE.2"]
rg.groupby("Round")["Acematch"].mean()

Round
1    13.476190
2    13.193548
3    12.562500
4     9.125000
5     7.000000
6    10.000000
7     6.000000
Name: Acematch, dtype: float64

5. Filtrer les matchs pour lesquels au moins une des variables `DBF.1` et `DBF.2` est manquante.

In [17]:
rg[rg[["DBF.1", "DBF.2"]].isna().any(axis=1)]

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Acematch
56,Simone Bolelli,Yen-Hsun Lu,1,0,0,3,63,33,37,12,...,11,4,6,78,6,6,2.0,NaN,NaN,8
63,Somdev Devvarman,Roger Federer,2,0,0,3,61,19,39,16,...,14,19,30,88,6,6,6.0,NaN,NaN,5

6. Remplacer les valeurs manquantes de `DBF.1` par zéro avec la méthode `loc`.

In [18]:
rg.loc[rg["DBF.1"].isna(), "DBF.1"] = 0
rg[rg[["DBF.1"]].isna().any(axis=1)]

Empty DataFrame
Columns: [Player1, Player2, Round, Result, FNL.1, FNL.2, FSP.1, FSW.1, SSP.1, SSW.1, ACE.1, DBF.1, WNR.1, UFE.1, BPC.1, BPW.1, NPA.1, NPW.1, TPW.1, ST1.1, ST2.1, ST3.1, ST4.1, ST5.1, FSP.2, FSW.2, SSP.2, SSW.2, ACE.2, DBF.2, WNR.2, UFE.2, BPC.2, BPW.2, NPA.2, NPW.2, TPW.2, ST1.2, ST2.2, ST3.2, ST4.2, ST5.2, Acematch]
Index: []

[0 rows x 43 columns]

7. Remplacer les valeurs manquantes de `DBF.2` par zéro avec la méthode `fillna`.

In [19]:
rg["DBF.2"] = rg["DBF.2"].fillna(0)
rg[rg[["DBF.2"]].isna().any(axis=1)]

Empty DataFrame
Columns: [Player1, Player2, Round, Result, FNL.1, FNL.2, FSP.1, FSW.1, SSP.1, SSW.1, ACE.1, DBF.1, WNR.1, UFE.1, BPC.1, BPW.1, NPA.1, NPW.1, TPW.1, ST1.1, ST2.1, ST3.1, ST4.1, ST5.1, FSP.2, FSW.2, SSP.2, SSW.2, ACE.2, DBF.2, WNR.2, UFE.2, BPC.2, BPW.2, NPA.2, NPW.2, TPW.2, ST1.2, ST2.2, ST3.2, ST4.2, ST5.2, Acematch]
Index: []

[0 rows x 43 columns]

8. Extraire la liste des participants à partir des colonnes `Player1` et `Player2`. Une façon de faire consiste à utiliser `concat` et la méthode `drop_duplicates` pour obtenir le résultat sous la forme d'une série et de la convertir en dataframe avec la méthode `to_frame`.

In [23]:
match_df = pd.concat([rg["Player1"], rg["Player2"]]).drop_duplicates().to_frame(name="joueur").reset_index(drop=True)
match_df

                  joueur
0    Pablo Carreno-Busta
1       Somdev Devvarman
2           Tobias Kamke
3       Julien Benneteau
4            Lukas Lacko
..                   ...
122          Yen-Hsun Lu
123      Grigor Dimitrov
124          Guido Pella
125         David Goffin
126     Janko Tipsarevic

[127 rows x 1 columns]

9. Écrire une fonction `n_match` qui prend une chaîne de caractères `joueur` en entrée et retourne le nombre de matchs disputés par le joueur.

In [24]:
joueur = "Pablo Carreno-Busta"
#si je veux juste pour ce joueur , on a 
len(rg[(rg["Player1"] == joueur)|(rg["Player2"]==joueur)])

1

In [26]:
def n_match(joueur):
    return len(rg[(rg["Player1"] == joueur)|(rg["Player2"]==joueur)])

match_df[n_match] = match_df["joueur"].apply(n_match)

match_df

ValueError: Operands are not aligned. Do `left, right = left.align(right, axis=1, copy=False)` before operating.

10. Utiliser les deux question précédentes et la méthode `apply` pour compter le nombre de matchs que chaque participant a disputé et ordonner le résultat par ordre décroissant.

11. Charger maintenant le jeu de données relatif au tournoi de Wimbledon dans un dataframe `wb` à partir du fichier `wimbledon2013.csv`.

In [27]:
wb = pd.read_csv("data/wimbledon2013.csv")
wb

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPC.2,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2
0,B.Becker,A.Murray,1,0,0,3,59,29,41,14,...,10,5,23,17,NaN,6,6,6,NaN,NaN
1,J.Ward,Y-H.Lu,1,0,1,3,62,77,38,35,...,15,2,46,39,NaN,6,6,7,7.0,NaN
2,N.Mahut,J.Hajek,1,1,3,0,72,44,28,10,...,1,0,19,12,NaN,2,4,3,NaN,NaN
3,T.Robredo,A.Bogomolov Jr.,1,1,3,0,77,40,23,12,...,0,0,22,13,NaN,2,2,4,NaN,NaN
4,R.Haase,M.Youzhny,1,0,0,3,68,61,32,15,...,21,3,44,30,NaN,6,7,7,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,D.Ferrer,J.Del Potro,5,0,0,3,68,45,32,17,...,8,3,21,17,NaN,6,6,7,NaN,NaN
110,N.Djokovic,T.Berdych,5,1,3,0,61,42,39,21,...,2,2,31,21,NaN,6,4,3,NaN,NaN
111,J.Janowicz,A.Murray,6,0,1,3,55,54,45,27,...,13,5,36,22,NaN,6,6,6,6.0,NaN
112,N.Djokovic,J.Del Potro,6,1,3,2,69,102,31,21,...,7,2,37,25,NaN,5,6,6,7.0,3.0
113,N.Djokovic,A.Murray,7,0,0,3,65,40,35,15,...,17,7,37,26,NaN,6,7,6,NaN,NaN

12. Ajouter une colonne `Tournoi` dans les dataframes `rg` et `wb` contenant respectivement les chaînes de caractères `"RG"` et `"WB"`.

In [29]:
wb["Tournoi"] = "WB"
wb

rg["Tournoi"] = "RG"

In [32]:
wb

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Tournoi
0,B.Becker,A.Murray,1,0,0,3,59,29,41,14,...,5,23,17,NaN,6,6,6,NaN,NaN,WB
1,J.Ward,Y-H.Lu,1,0,1,3,62,77,38,35,...,2,46,39,NaN,6,6,7,7.0,NaN,WB
2,N.Mahut,J.Hajek,1,1,3,0,72,44,28,10,...,0,19,12,NaN,2,4,3,NaN,NaN,WB
3,T.Robredo,A.Bogomolov Jr.,1,1,3,0,77,40,23,12,...,0,22,13,NaN,2,2,4,NaN,NaN,WB
4,R.Haase,M.Youzhny,1,0,0,3,68,61,32,15,...,3,44,30,NaN,6,7,7,NaN,NaN,WB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,D.Ferrer,J.Del Potro,5,0,0,3,68,45,32,17,...,3,21,17,NaN,6,6,7,NaN,NaN,WB
110,N.Djokovic,T.Berdych,5,1,3,0,61,42,39,21,...,2,31,21,NaN,6,4,3,NaN,NaN,WB
111,J.Janowicz,A.Murray,6,0,1,3,55,54,45,27,...,5,36,22,NaN,6,6,6,6.0,NaN,WB
112,N.Djokovic,J.Del Potro,6,1,3,2,69,102,31,21,...,2,37,25,NaN,5,6,6,7.0,3.0,WB
113,N.Djokovic,A.Murray,7,0,0,3,65,40,35,15,...,7,37,26,NaN,6,7,6,NaN,NaN,WB

In [35]:
rg_concat = rg.drop(columns="Acematch")
rg_concat

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,BPW.2,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Tournoi
0,Pablo Carreno-Busta,Roger Federer,1,0,0,3,62,27,38,11,...,7,14,18,88,6,6,6.0,NaN,NaN,RG
1,Somdev Devvarman,Daniel Munoz-De La Nava,1,1,3,0,62,54,38,22,...,16,22,25,106,3,3,5.0,NaN,NaN,RG
2,Tobias Kamke,Paolo Lorenzi,1,1,3,2,62,53,38,15,...,18,19,27,139,3,3,6.0,6.0,3.0,RG
3,Julien Benneteau,Ricardas Berankis,1,1,3,1,72,87,28,19,...,13,33,43,149,6,3,7.0,6.0,NaN,RG
4,Lukas Lacko,Sam Querrey,1,0,0,3,52,31,48,22,...,7,12,13,93,6,6,6.0,NaN,NaN,RG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,Rafael Nadal,Stanislas Wawrinka,5,1,3,0,75,40,25,11,...,5,16,30,64,2,3,1.0,NaN,NaN,RG
121,Novak Djokovic,Tommy Haas,5,1,3,0,64,41,36,22,...,2,2,17,84,3,6,5.0,NaN,NaN,RG
122,David Ferrer,Jo-Wilfried Tsonga,6,1,3,0,60,35,40,23,...,5,7,16,84,1,6,2.0,NaN,NaN,RG
123,Novak Djokovic,Rafael Nadal,6,0,2,3,67,76,33,30,...,16,15,26,177,6,3,6.0,6.0,9.0,RG
124,Rafael Nadal,David Ferrer,7,1,3,0,70,43,30,11,...,12,10,14,72,3,2,3.0,NaN,NaN,RG

13. Concaténer les deux dataframes dans un nouveau dataframe `tennis`.

In [37]:
tennis = pd.concat([rg,wb])
tennis

,Player1,Player2,Round,Result,FNL.1,FNL.2,FSP.1,FSW.1,SSP.1,SSW.1,...,NPA.2,NPW.2,TPW.2,ST1.2,ST2.2,ST3.2,ST4.2,ST5.2,Acematch,Tournoi
0,Pablo Carreno-Busta,Roger Federer,1,0,0,3,62,27,38,11,...,14,18,88.0,6,6,6.0,NaN,NaN,11.0,RG
1,Somdev Devvarman,Daniel Munoz-De La Nava,1,1,3,0,62,54,38,22,...,22,25,106.0,3,3,5.0,NaN,NaN,7.0,RG
2,Tobias Kamke,Paolo Lorenzi,1,1,3,2,62,53,38,15,...,19,27,139.0,3,3,6.0,6.0,3.0,10.0,RG
3,Julien Benneteau,Ricardas Berankis,1,1,3,1,72,87,28,19,...,33,43,149.0,6,3,7.0,6.0,NaN,27.0,RG
4,Lukas Lacko,Sam Querrey,1,0,0,3,52,31,48,22,...,12,13,93.0,6,6,6.0,NaN,NaN,14.0,RG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,D.Ferrer,J.Del Potro,5,0,0,3,68,45,32,17,...,21,17,NaN,6,6,7.0,NaN,NaN,NaN,WB
110,N.Djokovic,T.Berdych,5,1,3,0,61,42,39,21,...,31,21,NaN,6,4,3.0,NaN,NaN,NaN,WB
111,J.Janowicz,A.Murray,6,0,1,3,55,54,45,27,...,36,22,NaN,6,6,6.0,6.0,NaN,NaN,WB
112,N.Djokovic,J.Del Potro,6,1,3,2,69,102,31,21,...,37,25,NaN,5,6,6.0,7.0,3.0,NaN,WB
113,N.Djokovic,A.Murray,7,0,0,3,65,40,35,15,...,37,26,NaN,6,7,6.0,NaN,NaN,NaN,WB

14. Utiliser le dataframe `tennis` pour comparer le nombre moyen d'aces par match à chaque niveau du tournoi à Roland Garros et à Wimbledon. Afficher le résultat en format large.

In [40]:
format_long = tennis.assign(ACES=tennis["ACE.1"]+tennis["ACE.2"]).groupby(["Tournoi", "Round"])["ACES"].mean().reset_index()
format_long

   Tournoi  Round       ACES
0       RG      1  13.476190
1       RG      2  13.193548
2       RG      3  12.562500
3       RG      4   9.125000
4       RG      5   7.000000
5       RG      6  10.000000
6       RG      7   6.000000
7       WB      1  21.125000
8       WB      2  23.869565
9       WB      3  24.000000
10      WB      4  24.375000
11      WB      5  26.500000
12      WB      6  27.500000
13      WB      7  13.000000

In [41]:
format_large = format_long.pivot(index="Tournoi",columns="Round",values="ACES")
format_large

Round           1          2        3       4     5     6     7
Tournoi
RG       13.47619  13.193548  12.5625   9.125   7.0  10.0   6.0
WB       21.12500  23.869565  24.0000  24.375  26.5  27.5  13.0

15. Quelle différence y a-t-il dans le format des noms des joueurs entre les dataframes `rg` et `wb` ?

In [ ]:
#tt lettres ds dataset rg et seuelemnt 1ère lettre majascule prénom puis. ds dataset wb

16. Construire un dataframe `rg_victoires` avec les trois colonnes suivantes pour le tournoi de Roland Garros :
- `joueur` : nom du joueur tel qu'il est donné dans `rg`,
- `nom_joueur` : nom de famille du joueur uniquement,
- `n_victoire` : nombre de matchs gagnés dans le tournoi.

In [50]:
joueur = "Novak Djokovic"

nbvic1 = len(rg[(rg["Player1"] == joueur) & (rg["Result"] == 1)])
nbvic2 = len(rg[(rg["Player2"] == joueur) & (rg["Result"] == 1)])
nb_vic = nbvic1 + nbvic2
nb_vic

5

In [54]:
def nb_vicdiff(df, joueur):
    nbvic1 = len(rg[(rg["Player1"] == joueur) & (rg["Result"] == 1)])
    nbvic2 = len(rg[(rg["Player2"] == joueur) & (rg["Result"] == 1)])
    return nbvic1 + nbvic2

    nb_vic(rg,"Novak Djokovic")
nb_vicdiff

17. Construire un dataframe `wb_victoires` avec les trois colonnes suivantes pour le tournoi de Wimbledon :
- `joueur` : nom du joueur tel qu'il est donné dans `wb`,
- `nom_joueur` : nom de famille du joueur uniquement,
- `n_victoire` : nombre de matchs gagnés dans le tournoi.

18. Faire une jointure entre `rg_victoires` et `wb_victoires` sur la colonne `nom_joueur` pour comparer le nombre de victoires par tournoi pour chaque joueur. Expliquer la différence de résultat selon que la jointure est à gauche, à droite, intérieure ou extérieure.